### PR TITLE
Solid color option

### PR DESCRIPTION
**Pull request by IsaiahPapa**
Yoyo,
 
I was hoping for an option that didn't edit the layout of youtube, as I wanted to scan youtube the same but hide thumbnails.

I wanted to add a new option for "solid color". I was thinking of adding a color picker, but didn't wanna change too much at once.

My changes just hide the image element showing only the default grey background.

Let me know what you think,
Isaiah

### CODE REVIEW

**Review by domdomegg — CHANGES_REQUESTED** [review]
Thanks for the great PR! And sorry on my part for the delay in reviewing.

I think this is a useful feature that I'd be happy to accept. It already looks great on the homepage, both on desktop and mobile:

image

As implemented, it appears that it doesn't work correctly on the search and watch pages (e.g. I would expect grey boxes, like on the homepage, rather than just nothing):

image

image

Are you able to make the changes so that it also applies the appropriate CSS rules for these pages? Then I can get it merged and deployed ASAP :)

**Comment by IsaiahPapa** [comment]
Sorry about that, bit of an oversight.

I added classes to support the suggest videos and search results thumbnails. I also changed the background color to var(--yt-spec-additive-background). I was going to add support dark and light mode, but figured this was a better way to quickly support it.

Question unrelated to this PR, do you mind if I also add do another PR for a "work mode" option to disable thumbnails only during user set hours?

**Review by domdomegg — APPROVED** [review]

**Comment by domdomegg** [comment]
Thanks @IsaiahPapa :raised_hands:

Will publish shortly

**Comment by domdomegg** [comment]
Released in 2.3.0, published on Google Chrome, Mozilla Firefox and Microsoft Edge and extension stores (pending their review, it should be available to users within the next 24 hours).

**Pull request merged**
